Repository techequitycollaborative/legislation-tracker, pull requests merged in 2025-07, with the labels that each got.

#143 Created advocacy hub page + other changes
  app/advocacy_hub.py
  app/bills.py
  app/calendar_page.py
  app/committees.py
  app/db/query.py
  app/home.py
  app/legislators.py
  app/main.py
  app/my_dashboard.py
  app/org_dashboard.py
  app/utils/aggrid_styler.py
  app/utils/my_dashboard.py
  app/utils/org_dashboard.py
Labels: enhancement, high-priority

#142 129 enhance legislator page
  app/db/contact_table.sql
  app/db/dashboard_tables.sql
  app/db/process_committee_view.sql
  app/db/process_legislators_from_snapshot.sql
  app/db/query.py
  app/legislators.py
  app/utils/aggrid_styler.py
  app/utils/archived_utils/display_utils.py
  app/utils/general.py
  app/utils/legislators.py
Labels: enhancement

#145 Bill topics display in details container
  app/utils/bills.py
  app/utils/general.py
  app/utils/my_dashboard.py
  app/utils/org_dashboard.py
Labels: bug, enhancement, medium-priority

#148 updated letter references
  app/advocacy_hub.py
  app/ai_wg_dashboard.py
  app/calendar_page.py
  app/utils/my_dashboard.py
  app/utils/org_dashboard.py
Labels: medium-priority

#154 bill topic display updates
  app/bills.py
  app/utils/aggrid_styler.py
Labels: bug, critical-priority

#155 Update bills.py
  app/bills.py
Labels: bug, critical-priority
