Repository techequitycollaborative/legislation-tracker, pull requests merged in 2025-06, with the labels that each got.

#121 Auth password bugs
  app/main.py
  app/utils/authentication.py
Labels: bug, critical-priority

#123 Removed event type from appearing in the downloaded ics files
  app/calendar_page.py
Labels: bug

#130 Remove r bills + fix date filters + add last updated date
  app/bills.py
  app/db/archived_db/process_bill_history_view.sql
  app/db/archived_db/process_bills_view.sql
  app/db/archived_db/refresh_processed_bills.sql
  app/db/process_bills_from_snapshot.sql
  app/db/query.py
  app/utils/aggrid_styler.py
  app/utils/display_utils.py
Labels: bug, enhancement, critical-priority

#115 Committees page v1
  app/committees.py
  app/db/process_committee_assignment_view.sql
  app/db/process_committee_view.sql
  app/db/query.py
  app/home.py
  app/main.py
  app/utils/aggrid_styler.py
  app/utils/display_utils.py
Labels: enhancement, medium-priority
